@section('titleMediateca')
    Mediateca
@stop
@extends('indexMediateca')
@section('menuMediateca')
	@include('viewVentana.encabezadoVentana')
@endsection
@section('cuerpoMediateca')
	@include('viewMediateca.cuerpoTelesecundaria')
@endsection
@section('pieMediateca')
    @include('viewMediateca.pieMediateca')
@endsection